// Auto-generated by tools/generate-mappers.ts
import { missions, Prisma } from "@prisma/client";
import { MissionsEntity } from "../../entities/missions/missions.entity";

export class MissionsMapper {
  static prismaToEntity(
    model: Prisma.missionsGetPayload<{}>
  ): MissionsEntity {
    const mapped: MissionsEntity = {
      id:
        model.id !== null && model.id !== undefined ? model.id.toString() : "",
      giverNpcId:
        model.giver_npc_id !== null && model.giver_npc_id !== undefined
          ? model.giver_npc_id.toString()
          : "",
      name:
        model.name !== null && model.name !== undefined
          ? model.name.toString()
          : "",
      description:
        model.description !== null && model.description !== undefined
          ? model.description.toString()
          : ""
    };

    return mapped;
  }

  static entityToPrisma(entity: MissionsEntity): missions {
    // ⚠️ Ajusta manualmente si tu modelo tiene campos obligatorios/autogenerados.
    return {
      id: entity.id as any,
      giver_npc_id: entity.giverNpcId as any,
      name: entity.name as any,
      description: entity.description as any,
    } as missions;
  }
}

export default MissionsMapper;
