// Auto-generated by tools/generate-mappers.ts
import { inventory_magic, Prisma } from "@prisma/client";
import { InventoryMagicEntity } from "../../entities/inventory_magic/inventoryMagic.entity";

export class InventoryMagicMapper {
  static prismaToEntity(
    model: Prisma.inventory_magicGetPayload<{
      
    }>
  ): InventoryMagicEntity {
    const mapped: InventoryMagicEntity = {
      id:
        model.id !== null && model.id !== undefined ? model.id.toString() : "",
      idUser:
        model.id_user !== null && model.id_user !== undefined
          ? model.id_user.toString()
          : "",
      idSpell:
        model.id_spell !== null && model.id_spell !== undefined
          ? model.id_spell.toString()
          : "",
      uses:
        model.uses !== null && model.uses !== undefined
          ? model.uses.toString()
          : "",
      level:
        model.level !== null && model.level !== undefined
          ? model.level.toString()
          : "",
    };

    return mapped;
  }

  static entityToPrisma(entity: InventoryMagicEntity): inventory_magic {
    // ⚠️ Ajusta manualmente si tu modelo tiene campos obligatorios/autogenerados.
    return {
      id: entity.id as any,
      id_user: entity.idUser as any,
      id_spell: entity.idSpell as any,
      uses: entity.uses as any,
      level: entity.level as any,
    } as inventory_magic;
  }
}

export default InventoryMagicMapper;
