import { weapon_rarity, weapon_weapon_type } from "../../enums";
import { InventoryWeaponEntity } from "../inventory_weapon/inventoryWeapon.entity";
import { NpcEntity } from "../npc/npc.entity";
import { ElementsEntity } from "../elements/elements.entity";
import { SkillUsageEntity } from "../skill_usage/skillUsage.entity";
import { TilesEntity } from "../tiles/tiles.entity";
import { ObjectsEntity } from "../objects/objects.entity";
export interface WeaponEntity {
  id: number;
  name: string;
  element_id?: number;
  damage_points_lvl1: number;
  damage_points_lvl2: number;
  damage_points_lvl3: number;
  damage_points_lvl4: number;
  damage_points_lvl5: number;
  upgrade_item_id: number;
  upgrade_cost_lvl2: number;
  upgrade_cost_lvl3: number;
  upgrade_cost_lvl4: number;
  upgrade_cost_lvl5: number;
  rarity: weapon_rarity;
  durability: number;
  durability_max: number;
  chipping?: number;
  ammo?: number;
  weapon_type: weapon_weapon_type;
  location_id?: number;
  skill_usage?: number;
  dice_needed?: number;
  found?: number;
  price_sell: number;
  price_buy: number;
  description: string;
  image?: string;
  inventory_weapon?: InventoryWeaponEntity[];
  npc?: NpcEntity[];
  elements?: ElementsEntity;
  skill_usage_weapon_skill_usageToskill_usage?: SkillUsageEntity;
  tiles?: TilesEntity;
  objects?: ObjectsEntity;
}
