// Auto-generated by tools/generate-mappers.ts
import { tiles, Prisma } from "@prisma/client";
import { TilesEntity } from "../../entities/tiles/tiles.entity";

export class TilesMapper {
  static prismaToEntity(
    model: Prisma.tilesGetPayload<{
    }>
  ): TilesEntity {
    const mapped: TilesEntity = {
      id:
        model.id !== null && model.id !== undefined ? model.id.toString() : "",
      name:
        model.name !== null && model.name !== undefined
          ? model.name.toString()
          : "",
      image:
        model.image !== null && model.image !== undefined
          ? model.image.toString()
          : "",
      structureId:
        model.structure_id !== null && model.structure_id !== undefined
          ? model.structure_id.toString()
          : "",
    };

    return mapped;
  }

  static entityToPrisma(entity: TilesEntity): tiles {
    // ⚠️ Ajusta manualmente si tu modelo tiene campos obligatorios/autogenerados.
    return {
      id: entity.id as any,
      name: entity.name as any,
      image: entity.image as any,
      structure_id: entity.structureId as any,
    } as tiles;
  }
}

export default TilesMapper;
