// Auto-generated by tools/generate-mappers.ts
import { loottables, Prisma } from "@prisma/client";
import { LoottablesEntity } from "../../entities/loottables/loottables.entity";

export class LoottablesMapper {
  static prismaToEntity(
    model: Prisma.loottablesGetPayload<{

    }>
  ): LoottablesEntity {
    const mapped: LoottablesEntity = {
      id:
        model.id !== null && model.id !== undefined ? model.id.toString() : "",
      idNpc:
        model.id_npc !== null && model.id_npc !== undefined
          ? model.id_npc.toString()
          : "",
      idMonster:
        model.id_monster !== null && model.id_monster !== undefined
          ? model.id_monster.toString()
          : "",
      idObject:
        model.id_object !== null && model.id_object !== undefined
          ? model.id_object.toString()
          : "",
      amount:
        model.amount !== null && model.amount !== undefined
          ? model.amount.toString()
          : "",
    };

    return mapped;
  }

  static entityToPrisma(entity: LoottablesEntity): loottables {
    // ⚠️ Ajusta manualmente si tu modelo tiene campos obligatorios/autogenerados.
    return {
      id: entity.id as any,
      id_npc: entity.idNpc as any,
      id_monster: entity.idMonster as any,
      id_object: entity.idObject as any,
      amount: entity.amount as any,
    } as loottables;
  }
}

export default LoottablesMapper;
