import { AttacksEntity } from "../attacks/attacks.entity";
import { LoottablesEntity } from "../loottables/loottables.entity";
import { MissionsEntity } from "../missions/missions.entity";
import { RacesEntity } from "../races/races.entity";
import { AffinityEntity } from "../affinity/affinity.entity";
import { ArmorEntity } from "../armor/armor.entity";
import { WeaponEntity } from "../weapon/weapon.entity";
import { HakiTypesEntity } from "../haki_types/hakiTypes.entity";
import { DevilFruitEntity } from "../devil_fruit/devilFruit.entity";
import { NpcInventoryEntity } from "../npc_inventory/npcInventory.entity";
import { PlayableCharacterJournalEntity } from "../playable_character_journal/playableCharacterJournal.entity";
export interface NpcEntity {
  id: number;
  name: string;
  biography: string;
  id_race: number;
  strength: number;
  dexterity: number;
  defense: number;
  aim: number;
  vision: number;
  speed: number;
  handcraft: number;
  agility: number;
  charisma: number;
  wisdom: number;
  affinity_id: number;
  chronicler_status: number;
  image_reference: string;
  boss_image_reference?: string;
  armor_id?: number;
  weapon_id?: number;
  haki_level?: number;
  haki_type?: number;
  devil_fruit_id?: number;
  health: number;
  max_health: number;
  attacks?: AttacksEntity[];
  loottables?: LoottablesEntity[];
  missions?: MissionsEntity[];
  races?: RacesEntity;
  affinity?: AffinityEntity;
  armor?: ArmorEntity;
  weapon?: WeaponEntity;
  haki_types?: HakiTypesEntity;
  devil_fruit?: DevilFruitEntity;
  npc_inventory?: NpcInventoryEntity[];
  playable_character_journal?: PlayableCharacterJournalEntity[];
}
