// Auto-generated by tools/generate-mappers.ts
import { haki_types, Prisma } from "@prisma/client";
import { HakiTypesEntity } from "../../entities";
import { ObjectParserForMapper } from "../../helpers/ObjectParserForMapper.helper";

export class HakiTypesMapper {
  static prismaToEntity(
    model: Prisma.haki_typesGetPayload<{
      include: {
        skill_usage:true,
        npc:true,
        playable_character:true
      };
    }>
  ): HakiTypesEntity {
    const mapped: HakiTypesEntity = {
      id:
        model.id !== null && model.id !== undefined ? model.id.toString() : "",
      name:
        model.name !== null && model.name !== undefined
          ? model.name.toString()
          : "",
      description:
        model.description !== null && model.description !== undefined
          ? model.description.toString()
          : "",
      skillBonused:
        model.skill_bonused !== null && model.skill_bonused !== undefined
          ? model.skill_bonused.toString()
          : "",
      skillUsage: model.skill_usage ? ObjectParserForMapper(model.skill_usage) : undefined,
      npc: model.npc ? ObjectParserForMapper(model.npc) : undefined,
      playableCharacter: model.playable_character
        ? ObjectParserForMapper(model.playable_character)
        : undefined,
    };

    return mapped;
  }

  static entityToPrisma(entity: HakiTypesEntity): haki_types {
    // ⚠️ Ajusta manualmente si tu modelo tiene campos obligatorios/autogenerados.
    return {
      id: entity.id as any,
      name: entity.name as any,
      description: entity.description as any,
      skill_bonused: entity.skillBonused as any,
    } as haki_types;
  }
}

export default HakiTypesMapper;
