// Auto-generated by tools/generate-mappers.ts
import { inventory_weapon, Prisma } from "@prisma/client";
import { InventoryWeaponEntity } from '../../entities/inventory_weapon/inventoryWeapon.entity';

export class InventoryWeaponMapper {
  static prismaToEntity(
    model: Prisma.inventory_weaponGetPayload<{
      
    }>
  ): InventoryWeaponEntity {
    const mapped: InventoryWeaponEntity = {
      id:
        model.id !== null && model.id !== undefined ? model.id.toString() : "",
      idUser:
        model.id_user !== null && model.id_user !== undefined
          ? model.id_user.toString()
          : "",
      idWeapon:
        model.id_weapon !== null && model.id_weapon !== undefined
          ? model.id_weapon.toString()
          : "",
      level:
        model.level !== null && model.level !== undefined
          ? model.level.toString()
          : "",
    };

    return mapped;
  }

  static entityToPrisma(entity: InventoryWeaponEntity): inventory_weapon {
    // ⚠️ Ajusta manualmente si tu modelo tiene campos obligatorios/autogenerados.
    return {
      id: entity.id as any,
      id_user: entity.idUser as any,
      id_weapon: entity.idWeapon as any,
      level: entity.level as any,
    } as inventory_weapon;
  }
}

export default InventoryWeaponMapper;
