// Auto-generated by tools/generate-mappers.ts
import { inventory_armor, Prisma } from "@prisma/client";
import { InventoryArmorEntity } from "../../entities/inventory_armor/inventoryArmor.entity";

export class InventoryArmorMapper {
  static prismaToEntity(
    model: Prisma.inventory_armorGetPayload<{

    }>
  ): InventoryArmorEntity {
    const mapped: InventoryArmorEntity = {
      id:
        model.id !== null && model.id !== undefined ? model.id.toString() : "",
      idUser:
        model.id_user !== null && model.id_user !== undefined
          ? model.id_user.toString()
          : "",
      idArmor:
        model.id_armor !== null && model.id_armor !== undefined
          ? model.id_armor.toString()
          : "",
      level:
        model.level !== null && model.level !== undefined
          ? model.level.toString()
          : "",
    };

    return mapped;
  }

  static entityToPrisma(entity: InventoryArmorEntity): inventory_armor {
    // ⚠️ Ajusta manualmente si tu modelo tiene campos obligatorios/autogenerados.
    return {
      id: entity.id as any,
      id_user: entity.idUser as any,
      id_armor: entity.idArmor as any,
      level: entity.level as any,
    } as inventory_armor;
  }
}

export default InventoryArmorMapper;
