// Auto-generated by tools/generate-mappers.ts
import { armor, Prisma, objects_rarity } from '@prisma/client';
import { ArmorEntity } from "../../entities/armor/armor.entity";
import { ObjectParserForMapper } from '../../helpers/ObjectParserForMapper.helper';
import { armor_rarity as PrismaArmorRarity } from "@prisma/client";
import { armor_rarity as DomainArmorRarity } from '../../enums/armor_rarity'

export class ArmorMapper {
  static prismaToEntity(
    model: Prisma.armorGetPayload<{
      include: {
        elements:true,
        objects:true,
        tiles:true,
      };
    }>
  ): ArmorEntity {
    const mapped: ArmorEntity = {
      id:
        model.id !== null && model.id !== undefined ? model.id.toString() : "",
      name:
        model.name !== null && model.name !== undefined
          ? model.name.toString()
          : "",
      elementId:
        model.element_id !== null && model.element_id !== undefined
          ? model.element_id.toString()
          : "",
      defensivePointsLvl1:
        model.defensive_points_lvl1 !== null &&
        model.defensive_points_lvl1 !== undefined
          ? model.defensive_points_lvl1.toString()
          : "",
      defensivePointsLvl2:
        model.defensive_points_lvl2 !== null &&
        model.defensive_points_lvl2 !== undefined
          ? model.defensive_points_lvl2.toString()
          : "",
      defensivePointsLvl3:
        model.defensive_points_lvl3 !== null &&
        model.defensive_points_lvl3 !== undefined
          ? model.defensive_points_lvl3.toString()
          : "",
      defensivePointsLvl4:
        model.defensive_points_lvl4 !== null &&
        model.defensive_points_lvl4 !== undefined
          ? model.defensive_points_lvl4.toString()
          : "",
      defensivePointsLvl5:
        model.defensive_points_lvl5 !== null &&
        model.defensive_points_lvl5 !== undefined
          ? model.defensive_points_lvl5.toString()
          : "",
      upgradeItemId:
        model.upgrade_item_id !== null && model.upgrade_item_id !== undefined
          ? model.upgrade_item_id.toString()
          : "",
      upgradeCostLvl2:
        model.upgrade_cost_lvl2 !== null &&
        model.upgrade_cost_lvl2 !== undefined
          ? model.upgrade_cost_lvl2.toString()
          : "",
      upgradeCostLvl3:
        model.upgrade_cost_lvl3 !== null &&
        model.upgrade_cost_lvl3 !== undefined
          ? model.upgrade_cost_lvl3.toString()
          : "",
      upgradeCostLvl4:
        model.upgrade_cost_lvl4 !== null &&
        model.upgrade_cost_lvl4 !== undefined
          ? model.upgrade_cost_lvl4.toString()
          : "",
      upgradeCostLvl5:
        model.upgrade_cost_lvl5 !== null &&
        model.upgrade_cost_lvl5 !== undefined
          ? model.upgrade_cost_lvl5.toString()
          : "",
      rarity: model.rarity !== undefined ? (DomainArmorRarity[model.rarity as keyof typeof PrismaArmorRarity]) : DomainArmorRarity.COMMON,
      locationId:
        model.location_id !== null && model.location_id !== undefined
          ? model.location_id.toString()
          : "",
      skillUsage:
        model.skill_usage !== null && model.skill_usage !== undefined
          ? model.skill_usage.toString()
          : "",
      diceNeeded:
        model.dice_needed !== null && model.dice_needed !== undefined
          ? model.dice_needed.toString()
          : "",
      found:
        model.found !== null && model.found !== undefined
          ? model.found.toString()
          : "",
      priceSell:
        model.price_sell !== null && model.price_sell !== undefined
          ? model.price_sell.toString()
          : "",
      priceBuy:
        model.price_buy !== null && model.price_buy !== undefined
          ? model.price_buy.toString()
          : "",
      description:
        model.description !== null && model.description !== undefined
          ? model.description.toString()
          : "",
      image:
        model.image !== null && model.image !== undefined
          ? model.image.toString()
          : "",
      elements: model.elements ? {
        id: model.elements.id.toString(),
        name: model.elements.name
      } : undefined,
      tiles: model.tiles ? {
        id: model.tiles.id.toString(),
        name: model.tiles.name,
        image: model.tiles.image,
        structureId: model.tiles.structure_id.toString()
      } : undefined,
      objects: model.objects ? ObjectParserForMapper(model.objects) : undefined,
    };

    return mapped;
  }

  static entityToPrisma(entity: ArmorEntity): armor {
    // ⚠️ Ajusta manualmente si tu modelo tiene campos obligatorios/autogenerados.
    return {
      id: entity.id as any,
      name: entity.name as any,
      element_id: entity.elementId as any,
      defensive_points_lvl1: entity.defensivePointsLvl1 as any,
      defensive_points_lvl2: entity.defensivePointsLvl2 as any,
      defensive_points_lvl3: entity.defensivePointsLvl3 as any,
      defensive_points_lvl4: entity.defensivePointsLvl4 as any,
      defensive_points_lvl5: entity.defensivePointsLvl5 as any,
      upgrade_item_id: entity.upgradeItemId as any,
      upgrade_cost_lvl2: entity.upgradeCostLvl2 as any,
      upgrade_cost_lvl3: entity.upgradeCostLvl3 as any,
      upgrade_cost_lvl4: entity.upgradeCostLvl4 as any,
      upgrade_cost_lvl5: entity.upgradeCostLvl5 as any,
      rarity: entity.rarity as any,
      location_id: entity.locationId as any,
      skill_usage: entity.skillUsage as any,
      dice_needed: entity.diceNeeded as any,
      found: entity.found as any,
      price_sell: entity.priceSell as any,
      price_buy: entity.priceBuy as any,
      description: entity.description as any,
      image: entity.image as any,
    } as armor;
  }
}

export default ArmorMapper;
