// Auto-generated by tools/generate-mappers.ts
import { npc_inventory, Prisma } from "@prisma/client";
import { NpcInventoryEntity } from "../../entities";

export class NpcInventoryMapper {
  static prismaToEntity(
    model: Prisma.npc_inventoryGetPayload<{
      
    }>
  ): NpcInventoryEntity {
    const mapped: NpcInventoryEntity = {
      id:
        model.id !== null && model.id !== undefined ? model.id.toString() : "",
      idNpc:
        model.id_npc !== null && model.id_npc !== undefined
          ? model.id_npc.toString()
          : "",
      idObject:
        model.id_object !== null && model.id_object !== undefined
          ? model.id_object.toString()
          : "",
      quantity:
        model.quantity !== null && model.quantity !== undefined
          ? model.quantity.toString()
          : "",
    };

    return mapped;
  }

  static entityToPrisma(entity: NpcInventoryEntity): npc_inventory {
    // ⚠️ Ajusta manualmente si tu modelo tiene campos obligatorios/autogenerados.
    return {
      id: entity.id as any,
      id_npc: entity.idNpc as any,
      id_object: entity.idObject as any,
      quantity: entity.quantity as any,
    } as npc_inventory;
  }
}

export default NpcInventoryMapper;
