// Auto-generated by tools/generate-mappers.ts
import { elements, Prisma } from "@prisma/client";
import { ElementsEntity } from "../../entities/elements/elements.entity";

export class ElementsMapper {
  static prismaToEntity(
    model: Prisma.elementsGetPayload<{
    }>
  ): ElementsEntity {
    const mapped: ElementsEntity = {
      id:
        model.id !== null && model.id !== undefined ? model.id.toString() : "",
      name:
        model.name !== null && model.name !== undefined
          ? model.name.toString()
          : "",
    };

    return mapped;
  }

  static entityToPrisma(entity: ElementsEntity): elements {
    // ⚠️ Ajusta manualmente si tu modelo tiene campos obligatorios/autogenerados.
    return {
      id: entity.id as any,
      name: entity.name as any,
    } as elements;
  }
}

export default ElementsMapper;
