// Auto-generated by tools/generate-mappers.ts
import { skill_usage, Prisma } from "@prisma/client";
import { SkillUsageEntity } from "../../entities";

export class SkillUsageMapper {
  static prismaToEntity(
    model: Prisma.skill_usageGetPayload<{
    }>
  ): SkillUsageEntity {
    const mapped: SkillUsageEntity = {
      id:
        model.id !== null && model.id !== undefined ? model.id.toString() : "",
      name:
        model.name !== null && model.name !== undefined
          ? model.name.toString()
          : "",
    };

    return mapped;
  }

  static entityToPrisma(entity: SkillUsageEntity): skill_usage {
    // ⚠️ Ajusta manualmente si tu modelo tiene campos obligatorios/autogenerados.
    return {
      id: entity.id as any,
      name: entity.name as any,
    } as skill_usage;
  }
}

export default SkillUsageMapper;
